### ISSUE TITLE
Just to say thanks!

### ISSUE THREAD

**Issue by gcaplan** [treeform/chrono#5]
This isn't an issue as such - hope you don't mind.

I just wanted to complement you for your work here - it's the best designed DateTime library I've ever seen, and I've been mucking about with code since the days of punch-cards.

In so many languages DateTime is a nightmare. Have you ever had to work with the recent Java implementation? 

I've always preferred to normalise to timestamps. Most databases can handle any arithmetic just fine, and you have fewer issues with serialising and storage. Parsing every incoming date into a huge great class rarely makes sense, especially if you are using the dates lazily and much of that CPU effort never even gets used. 

But choosing to normalise to timestamps has generally meant hacking together an ad-hoc utility library to use them. It's a great treat to find something far more comprehensive and elegant is available off the shelf!

You've saved me hours of work, so I just wanted to say thanks.

**Comment by treeform** [comment]
I been mucking with code since Windows 98, and this is the best complement I have received for my open source stuff, thanks!

I fought with Java, Python and JavaScript datetimes. They all had issues. I had to do a ton of timezone conversions when making airline booking software. Every timezone on earth was involved.
